Update sonar.yml

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -6,7 +6,6 @@ env:
   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}           # Token de acceso de SonarCloud
   PHP_VERSION: '8.2'                                 # Versión de PHP
   SONAR_SCANNER_VERSION: '4.8.0.2856'                # Versión de SonarScanner
-  JAVA_VERSION: '17'                                 # Versión de Java necesaria
 
 on:
   push:
@@ -28,12 +27,6 @@ jobs:
           php-version: ${{ env.PHP_VERSION }}
           extensions: mbstring, xml, curl                # Extensiones de PHP necesarias
 
-      - name: Install Java
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y openjdk-17-jdk
-          java -version  # Verifica la instalación de Java
-
       - name: Install Composer
         run: |
           curl -sS https://getcomposer.org/installer | php
@@ -47,10 +40,14 @@ jobs:
       - name: Install SonarScanner
         run: |
           curl -sS -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip -o sonar-scanner.zip
+          if [[ ! -f sonar-scanner.zip || ! unzip -tq sonar-scanner.zip ]]; then
+            echo "Error: Failed to download a valid SonarScanner zip file."
+            exit 1
+          fi
           unzip sonar-scanner.zip
           mv sonar-scanner-* sonar-scanner
           sudo mv sonar-scanner /opt/sonar-scanner
-          echo '/opt/sonar-scanner/bin' >> $GITHUB_PATH    # Agrega al PATH
+          echo 'PATH=/opt/sonar-scanner/bin:$PATH' >> $GITHUB_ENV
           rm sonar-scanner.zip                             # Limpieza del archivo zip descargado
 
       - name: Run SonarScanner
